name: pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: jay-withers/workflows/.github/workflows/pre-commit.yml@1f4d0ce8f5c5565d003f5f70dc7c174912206734 # v1.0.0
