name: test-install

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/test-install.yml"

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run setup
        run: bash src/setup.sh

  macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run setup
        run: bash src/setup.sh
